version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    volumes:
      - ./target/keycloak-db-user-federation-1.0.8.jar:/opt/keycloak/providers/keycloak-db-user-federation-1.0.8.jar
    # - ./src/test/resources/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - start-dev
