
CREATE TABLE users (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username        varchar(40) NOT NULL,
    email           varchar(40) NOT NULL,
    email_verified  boolean     NOT NULL DEFAULT false,
    first_name      varchar(40) NOT NULL,
    last_name       varchar(40) NOT NULL,
    enabled         boolean     NOT NULL DEFAULT true,
    updated         timestamp   NOT NULL,
    my_attr         varchar(40)
);

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('booby', 'bobby@barbarian.com', true, 'Bobby', 'Barbarian', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('eric', 'eric@cavalier.com', true, 'Eric', 'Cavalier', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('diana', 'diana@acrobat.com', true, 'Diana', 'Acrobat', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('hank', 'hank@ranger.com', true, 'Hank', 'Ranger', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('presto', 'presto@wizard.com', true, 'Presto', 'Wizard', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, updated)
    VALUES ('sheila', 'sheila@thief.com', true, 'Sheila', 'Thief', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, enabled, updated, my_attr)
    VALUES ('uni', 'uni@unicorn.com', false, 'Uni', 'Unicorn', false, now(), 'my value');
