
CREATE TABLE users (
    id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username         varchar(40) NOT NULL,
    email            varchar(40) NOT NULL,
    -- Some DB not support boolean data type, like old oracle :(
    email_verified   varchar(1)   NOT NULL DEFAULT 'Y',
    first_name       varchar(40) NOT NULL,
    last_name        varchar(40) NOT NULL,
    enabled          boolean     NOT NULL DEFAULT true,
    temp_password    varchar(40),
    required_actions varchar(80),
    updated          timestamp   NOT NULL DEFAULT now(),
    -- Custom attributes
    ability          varchar(40)
);

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, required_actions, updated)
    VALUES ('bobby', 'bobby@barbarian.com', 'y', 'Bobby', 'Barbarian', 'ThunderClub', 'VERIFY_EMAIL, UPDATE_PROFILE,UPDATE_PASSWORD , TERMS_AND_CONDITIONS ', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, required_actions, updated)
    VALUES ('eric', 'eric@fighter.com', 'y', 'Eric', 'Fighter', 'GriffonShield', 'VERIFY_EMAIL', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, required_actions, updated)
    VALUES ('diana', 'diana@monk.com', 'y', 'Diana', 'Monk', 'JavelinStaff', 'UPDATE_PROFILE', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, required_actions, updated)
    VALUES ('hank', 'hank@ranger.com', 'y', 'Hank', 'Ranger', 'EnergyBow', 'UPDATE_PASSWORD', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, required_actions, updated)
    VALUES ('presto', 'presto@wizard.com', 'y', 'Presto', 'Wizard', 'HatofManySpells', 'VERIFY_PROFILE', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, temp_password, updated)
    VALUES ('sheila', 'sheila@thief.com', 'y', 'Sheila', 'Rogue', 'CloakofInvisibility', now());

INSERT INTO users (username, email, email_verified, first_name, last_name, enabled, updated, ability)
    VALUES ('uni', 'uni@unicorn.com', 'n', 'Uni', 'Unicorn', false, now(), 'teleport');


-- Invalid users

INSERT INTO users (username, email, first_name, last_name)
    VALUES ('', 'invalid@error.com', 'Invalid', 'Erro');

INSERT INTO users (username, email, first_name, last_name)
    VALUES ('invalid_email', 'invalid', 'Invalid', 'Erro');

INSERT INTO users (username, email, first_name, last_name)
    VALUES ('invalid_first_name', 'invalid@error.com', '', 'Invalid first name');

INSERT INTO users (username, email, first_name, last_name)
    VALUES ('invalid_last_name', 'invalid@error.com', 'Invalid', '');

INSERT INTO users (username, email, first_name, last_name, required_actions)
    VALUES ('invalid_action', 'invalid@error.com', 'Invalid', 'Erro', 'INVALID_ACTION');
